name: ESP-IDF build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.3
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          source "$IDF_PATH/export.sh"
          idf.py set-target esp32p4
          idf.py build
